import "../globals.css";
import Head from "next/head";
import { useLocale } from "next-intl";
import { notFound } from "next/navigation";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { SideMenu } from "@/components/SideMenu";
import { SideColumn } from "@/components/SideColumn";
import QueryClientProviderFC from "./QueryClientProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  const locale = useLocale();
  if (params.locale !== locale) {
    notFound();
  }
  return (
    <html lang={locale}>
      <body className={inter.className}>
        <QueryClientProviderFC>
          <div className="flex relative justify-center md:mx-auto h-screen">
            <SideMenu />
            <Head>
              <title>My page title</title>
            </Head>
            <div className="max-w-[600px] flex-1 border-r border-l border-slate-200 overflow-scroll scrollbar">
              {children}
            </div>
            <SideColumn />
          </div>
        </QueryClientProviderFC>
      </body>
    </html>
  );
}
