"use client";
import "../globals.css";
import Head from "next/head";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { SideMenu } from "@/components/SideMenu";
import { SideColumn } from "@/components/SideColumn";
import { QueryClientProvider, QueryClient } from "react-query";

const inter = Inter({ subsets: ["latin"] });
const queryClient = new QueryClient();

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <QueryClientProvider client={queryClient}>
          <div className="flex relative justify-center md:mx-auto h-screen">
            <SideMenu />
            <Head>
              <title>My page title</title>
            </Head>
            <div className="max-w-[600px] flex-1 border-r border-l border-slate-200 overflow-scroll scrollbar">
              {children}
            </div>
            <SideColumn />
          </div>
        </QueryClientProvider>
      </body>
    </html>
  );
}
